apiVersion: v1
kind: Service
metadata:
  name: result-app-service
spec:
  type: NodePort
  ports:
    - port: 5001
      targetPort: 8080
      nodePort: 30002
  
  selector:
    name: result-app-pod
    app: demo-result-app