apiVersion: v1
kind: Service
metadata:
  name: voting-app-service
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 8080
      nodePort: 30001
  selector:
    name: voting-app-pod
    app: demo-voting-app